# -*- coding: utf-8 -*-
"""regularexpression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1I3uFzxkqAMYnbvWYdFa7VFQV429uIglM
"""

vowels=["a","e","i","o","u","A","E","I","O","U"]

string=input("Enter a string - ")
cv=0
cd=0
cc=0
for i in range(0,len(string)):
  if string[i].isalpha():
    if string[i] in vowels:
      cv+=1
    else :
      cc+=1
  elif string[i].isdigit():
    cd+=1
print(f"Count of vowels is {cv}, consonants is {cc} and digits is{cd}")

import re

def matchOccurrences(text):
    pattern1 = r'\b[Aa]b*\b'  # Zero or more b's
    pattern2 = r'\b[Aa]b?\b'  # Zero or one b
    pattern3 = r'\b[Aa]b+\b'  # One or more b's
    pattern4 = r'\b[Aa]bbbbc\b'  # Four consecutive b's followed by a "c"

    occurrences1 = re.findall(pattern1, text)
    occurrences2 = re.findall(pattern2, text)
    occurrences3 = re.findall(pattern3, text)
    occurrences4 = re.findall(pattern4, text)

    return occurrences1, occurrences2, occurrences3, occurrences4


# Example usage
text = "Ab abb Ac Abbbbc Ad AB Abbbbcb"

occurrences1, occurrences2, occurrences3, occurrences4 = matchOccurrences(text)

print("Occurrences of zero or more b's:", occurrences1)
print("Occurrences of zero or one b:", occurrences2)
print("Occurrences of one or more b's:", occurrences3)
print("Occurrences of four consecutive b's followed by a 'c':", occurrences4)

import re
string=input("Enter a string - ")
vow=re.findall("[AEIOUaeiou]",string)
dig=re.findall("[0-9]",string)
cons=re.findall("[^AEIOUaeiou\W\d_]",string)
cc=len(cons)
cv=len(vow)
cd=len(dig)
print(f"Count of vowels is {cv}, consonants is {cc} and digits is{cd}")

import re

string = input("Enter USN: ")

if re.match(r"^1MS\d{2}[A-Za-z]{2}\d{3}$", string):
    print("Valid USN")
else:
    print("Invalid USN")

import random

def displayOddNumbers(numbers):
    odd_numbers = []
    for num in numbers:
        if num % 2 != 0 and len(str(num)) in [2, 4]:
            odd_numbers.append(num)
    return odd_numbers


numbers = []
for i in range(20):
    numbers.append(random.randint(1, 100))

odd_numbers = displayOddNumbers(numbers)

print("Random numbers:", numbers)
print("Odd numbers of length 2 and 4:", odd_numbers)

def searchAndReplace(pattern, replacement, string):
    locations = []
    start = 0
    while True:
        index = string.find(pattern, start)
        if index == -1:
            break
        locations.append(index)
        start = index + len(pattern)
    replaced_string = string.replace(pattern, replacement)
    return locations, replaced_string



string = "the world is full of hypocrites"
pattern = "the"
replacement = "a"

locations, replaced_string = searchAndReplace(pattern, replacement, string)

print("Original string:", string)
print("Pattern:", pattern)
print("Replacement:", replacement)
print("Locations of pattern:", locations)
print("Replaced string:", replaced_string)